### ISSUE TITLE
[Bug] KubeJS & TFC Tooltip issue

### ISSUE THREAD

**Issue by Officialy** [GregTech-Intergalactical/AntimatterAPI#205]
### What happened?

When first starting the server with Antimatter, TerraFirmaCraft & KubeJS, it does not give the proper tooltips for food items and terrafirmacraft ore pieces.

Then when logging in to single player world, it works.
Then I log out of Single Player, log back in to the server (without restarting the client) and everything will work on both Server and Client.

When I restarted the server, without closing the client and log back in to the server world, everything is fine.
If I restart the client, while not restarting the server, its messed up again.
It then takes a log out, enter SP and log back in to server to fix it

### What mod loaders are you seeing the problem on?

Forge

### Relevant log output

```shell
https://gist.github.com/Officialy/4ba109af079e313ad48d93e2797897b9
```

### Anything else?

It seems this part is likely the cause: 
```

[00:39:59] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot read field "scriptManager" because "dev.latvian.mods.kubejs.server.ServerScriptManager.instance" is null
	at dev.latvian.mods.kubejs.script.ScriptType.lambda$static$1(ScriptType.java:24) ~[kubejs-forge-1802.5.5-build.567.jar%2357!/:1802.5.5-build.567]
	at dev.latvian.mods.kubejs.event.EventJS.post(EventJS.java:31) ~[kubejs-forge-1802.5.5-build.567.jar%2357!/:1802.5.5-build.567]
	at muramasa.antimatter.integration.kubejs.RecipeLoaderEventKubeJS.createAndPost(RecipeLoaderEventKubeJS.java:29) ~[AntimatterAPI-1.18.2-0.1.jar%2353!/:1.18.2-0.1]
	at muramasa.antimatter.AntimatterDynamics.onRecipeCompile(AntimatterDynamics.java:139) ~[AntimatterAPI-1.18.2-0.1.jar%2353!/:1.18.2-0.1]
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed Antimatter and Tesseract are up to date.

- [X] Yes

**Comment by Trinsdar** [comment]
fixed in dev
