### ISSUE TITLE
[Bug] Game crash

### ISSUE THREAD

**Issue by vlad-wild** [GregTech-Intergalactical/AntimatterAPI#221]
### What happened?

I don't know what happened, but when I opened the creative tab [Tools], the game crashes.
Not last commit. This is [0.2-rc12-1.18.2](https://github.com/GregTech-Intergalactical/AntimatterAPI/releases/tag/0.2-rc12-1.18.2)

### What mod loaders are you seeing the problem on?

Forge 40.2.9

### Relevant log output

```shell
[08:42:00] [Sound engine/ERROR]: Stop: Invalid name parameter.
[08:42:01] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: mouseReleased event handler
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:535) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2349!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2345!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2349!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1068) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%2318!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.AbstractMethodError: Method muramasa/antimatter/capability/energy/ItemEnergyHandler.serializeNBT()Lnet/minecraft/nbt/Tag; is abstract
	at muramasa.antimatter.capability.energy.ItemEnergyHandler.serializeNBT(ItemEnergyHandler.java) ~[AntimatterAPI-forge-0.2-rc12-1.18.2.jar%2359!/:0.2-rc12-1.18.2]
	at tesseract.api.forge.Provider.lambda$serializeNBT$0(Provider.java:30) ~[TesseractAPI-forge-1.18.2-0.2-hotfix.jar%23129!/:?]
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:195) ~[forge-1.18.2-40.2.9-universal.jar%23147!/:?]
	at tesseract.api.forge.Provider.serializeNBT(Provider.java:28) ~[TesseractAPI-forge-1.18.2-0.2-hotfix.jar%23129!/:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:115) ~[forge-1.18.2-40.2.9-universal.jar%23147!/:?]
	at net.minecraftforge.common.capabilities.CapabilityProvider.serializeCaps(CapabilityProvider.java:132) ~[forge-1.18.2-40.2.9-universal.jar%23147!/:?]
	at net.minecraft.world.item.ItemStack.m_41777_(ItemStack.java:404) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at muramasa.antimatter.tool.IAntimatterTool.onGenericFillItemGroup(IAntimatterTool.java:171) ~[AntimatterAPI-forge-0.2-rc12-1.18.2.jar%2359!/:0.2-rc12-1.18.2]
	at muramasa.antimatter.tool.MaterialTool.m_6787_(MaterialTool.java:121) ~[AntimatterAPI-forge-0.2-rc12-1.18.2.jar%2359!/:0.2-rc12-1.18.2]
	at net.minecraft.world.item.CreativeModeTab.m_6151_(CreativeModeTab.java:211) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_98560_(CreativeModeInventoryScreen.java:488) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_6348_(CreativeModeInventoryScreen.java:444) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at net.minecraft.client.MouseHandler.m_168078_(MouseHandler.java:96) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23142!/:?]
	... 25 more
[08:42:01] [Render thread/FATAL]: Preparing crash report with UUID 4247737e-808e-46d0-be8a-d1d643677ca2
[08:42:01] [Render thread/FATAL]: Preparing crash report with UUID a240362c-574a-4223-bebc-11409317a36a
```

### Anything else?

[crash-2023-06-17_08.42.01-client.txt](https://github.com/GregTech-Intergalactical/AntimatterAPI/files/11778068/crash-2023-06-17_08.42.01-client.txt)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed Antimatter and Tesseract are up to date.

- [X] Yes

**Comment by Trinsdar** [comment]
Closing cause this was probably fixed at some point in the devolpment, reopen if it happens with the curseforge version i'll be putting out in the next couple days or the latest action builds
