### ISSUE TITLE
[Feature request] Is it possible to make compatibility with VulKanMod?

### ISSUE THREAD

**Issue by Tentou-Reikie** [GregTech-Intergalactical/AntimatterAPI#231]
### What happened?

Incompatible with VulKanMod

### What mod loaders are you seeing the problem on?

Fabric

### Relevant log output

```shell
[19:19:19] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.15.10
[19:19:19] [ForkJoinPool-1-worker-2/WARN]: The mod "antimatter" contains invalid entries in its mod json:
- Unsupported root entry "credits" at line 13 column 12
[19:19:19] [main/WARN]: Warnings were found!
 - 模组 'Felt Enchanting API' (felt-enchanting-api) 1.0.0-1.18.2 建议安装 feltfabric 的 任意版本，但没有安装它！
	 - 为了最佳体验，您应该安装 feltfabric 的 任意版本。
[19:19:19] [main/INFO]: Loading 89 mods:
	- antimatter 0.2
	   |-- advanced_runtime_resource_pack 0.6.7
	   |-- felt-enchanting-api 1.0.0-1.18.2
	   |-- felt-player-item-api 1.0.0-1.18.2
	   |-- felt-recipe-api 1.0.0-1.18.2
	   |-- porting_lib 1.2.575-beta+1.18.2-stable
	   |    |-- forge_tags 2.1
	   |    |-- mm 2.3
	   |    \-- serialization_hooks 0.3.23
	   \-- structurelib 2.0.0-pre10
	        |-- forgeconfigapiport 3.2.4
	        |    |-- com_electronwill_night-config_core 3.6.5
	        |    \-- com_electronwill_night-config_toml 3.6.5
	        |-- porting_lib 1.2.575-beta+1.18.2-stable
	        |    |-- forge_tags 2.1
	        |    |-- mm 2.3
	        |    \-- serialization_hooks 0.3.23
	        \-- resourcefullib 0.0.5
	- fabric-api 0.77.0+1.18.2
	   |-- fabric-api-base 0.4.5+64b7c69360
	   |-- fabric-api-lookup-api-v1 1.6.3+2373a54560
	   |-- fabric-biome-api-v1 8.0.7+e83becad60
	   |-- fabric-block-api-v1 1.0.0+ee3621fc60
	   |-- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560
	   |-- fabric-command-api-v1 1.1.10+d7c144a860
	   |-- fabric-commands-v0 0.2.9+b4f4f6cd60
	   |-- fabric-containers-v0 0.1.24+d7c144a860
	   |-- fabric-content-registries-v0 3.1.3+c85f2e3860
	   |-- fabric-convention-tags-v1 1.1.0+43ce63a460
	   |-- fabric-crash-report-info-v1 0.2.1+ee261a3e60
	   |-- fabric-data-generation-api-v1 3.1.0+6c70b68e60
	   |-- fabric-dimensions-v1 2.1.21+489d6f8260
	   |-- fabric-entity-events-v1 1.4.9+d7c144a860
	   |-- fabric-events-interaction-v0 0.4.20+d7c144a860
	   |-- fabric-events-lifecycle-v0 0.2.22+d7c144a860
	   |-- fabric-game-rule-api-v1 1.0.13+d7c144a860
	   |-- fabric-item-api-v1 1.6.2+8165403660
	   |-- fabric-item-groups-v0 0.3.16+91896a4960
	   |-- fabric-key-binding-api-v1 1.0.12+54e5b2ec60
	   |-- fabric-keybindings-v0 0.2.10+b4f4f6cd60
	   |-- fabric-lifecycle-events-v1 2.1.1+cc71601c60
	   |-- fabric-loot-api-v2 1.1.2+1997ad1260
	   |-- fabric-loot-tables-v1 1.1.4+e747827960
	   |-- fabric-mining-level-api-v1 2.1.6+cc71601c60
	   |-- fabric-models-v0 0.3.7+d7c144a860
	   |-- fabric-networking-api-v1 1.0.24+2d30af4b60
	   |-- fabric-networking-v0 0.3.11+b4f4f6cd60
	   |-- fabric-object-builder-api-v1 2.1.5+032c981d60
	   |-- fabric-particles-v1 0.2.13+526dc1ac60
	   |-- fabric-registry-sync-v0 0.9.12+bb2e047760
	   |-- fabric-renderer-api-v1 0.5.0+bf48649860
	   |-- fabric-renderer-indigo 0.6.1+03e2b68760
	   |-- fabric-renderer-registries-v1 3.2.13+b4f4f6cd60
	   |-- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60
	   |-- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60
	   |-- fabric-rendering-v0 1.1.15+b4f4f6cd60
	   |-- fabric-rendering-v1 1.11.0+b7f3cf3460
	   |-- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
	   |-- fabric-resource-loader-v0 0.5.3+047a5ecb60
	   |-- fabric-screen-api-v1 1.0.11+d882b91560
	   |-- fabric-screen-handler-api-v1 1.2.3+1f6558e860
	   |-- fabric-textures-v0 1.0.13+3ac43d9560
	   |-- fabric-transfer-api-v1 1.6.4+f4563ac860
	   \-- fabric-transitive-access-wideners-v1 1.1.0+e747827960
	- fabricloader 0.15.10
	   \-- mixinextras 0.3.5
	- java 17
	- minecraft 1.18.2
	- tesseractapi 0.2.2
	   |-- botarium 2.0.5
	   |-- carbonconfig 1.1.1
	   \-- team_reborn_energy 2.3.0
	- vulkanmod 0.2.5
	   |-- org_joml_joml 1.10.4
	   |-- org_lwjgl_lwjgl 3.3.1
	   |-- org_lwjgl_lwjgl-glfw 3.3.1
	   |-- org_lwjgl_lwjgl-glfw_natives-linux 3.3.1
	   |-- org_lwjgl_lwjgl-glfw_natives-windows 3.3.1
	   |-- org_lwjgl_lwjgl-openal 3.3.1
	   |-- org_lwjgl_lwjgl-openal_natives-linux 3.3.1
	   |-- org_lwjgl_lwjgl-openal_natives-windows 3.3.1
	   |-- org_lwjgl_lwjgl-shaderc 3.3.1
	   |-- org_lwjgl_lwjgl-shaderc_natives-linux 3.3.1
	   |-- org_lwjgl_lwjgl-shaderc_natives-windows 3.3.1
	   |-- org_lwjgl_lwjgl-stb 3.3.1
	   |-- org_lwjgl_lwjgl-stb_natives-linux 3.3.1
	   |-- org_lwjgl_lwjgl-stb_natives-windows 3.3.1
	   |-- org_lwjgl_lwjgl-vma 3.3.1
	   |-- org_lwjgl_lwjgl-vma_natives-linux 3.3.1
	   |-- org_lwjgl_lwjgl-vma_natives-windows 3.3.1
	   |-- org_lwjgl_lwjgl-vulkan 3.3.1
	   |-- org_lwjgl_lwjgl_natives-linux 3.3.1
	   \-- org_lwjgl_lwjgl_natives-windows 3.3.1
[19:19:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/TenCraft_GTI_Fabric/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:19:19] [main/INFO]: Compatibility level set to JAVA_17
[19:19:19] [main/WARN]: Reference map 'carbonconfig-refmap.json' for mixins.carbonconfig.json could not be read. If this is a development environment you can ignore this message
[19:19:20] [main/INFO]: I used the json to destroy the json
[19:19:20] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[19:19:26] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[19:19:26] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:19:27] [Render thread/INFO]: Setting user: Tentou_Reikie
[19:19:27] [Render thread/INFO]: Loading Antimatter
[19:19:27] [Render thread/INFO]: Registration event DATA_INIT
[19:19:28] [Render thread/INFO]: Registration event DATA_READY
[19:19:28] [Render thread/INFO]: AntimatterAPI WorldGen Initialization Stage...
[19:19:28] [Render thread/INFO]: Registration event WORLDGEN_INIT
[19:19:28] [Render thread/INFO]: initializing
[19:19:28] [Render thread/INFO]: Definitely not up to no good
[19:19:29] [Render thread/INFO]: == VulkanMod ==
[19:19:29] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[19:19:29] [Render thread/INFO]: Time to run data providers: 301 ms.
[19:19:29] [Render thread/INFO]: Registration event CLIENT_DATA_INIT
[19:19:29] [Render thread/INFO]: Time to run asset providers: 394 ms.
[19:19:30] [Render thread/WARN]: Method overwrite conflict for getOffset in vulkanmod.mixins.json:render.VertexFormatMixin from mod vulkanmod, previously written by io.github.fabricators_of_create.porting_lib.mixin.client.VertexFormatMixin. Skipping method.
[19:19:30] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[19:19:30] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[19:19:30] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[19:19:31] [Render thread/INFO]: ARRP register - before vanilla
[19:19:31] [Render thread/INFO]: ARRP register - after vanilla
[19:19:31] [Render thread/INFO]: ARRP register - before user
[19:19:31] [Render thread/INFO]: closing rrp antimatter:data
[19:19:31] [Render thread/ERROR]: Mixin apply for mod porting_lib failed porting_lib.mixins.client.json:TextureManagerMixin from mod porting_lib -> net.minecraft.class_1060: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1060::port_lib$fixRelease with priority 1000 cannot inject into net/minecraft/class_1060::method_4615(Lnet/minecraft/class_2960;)V merged by net.vulkanmod.mixin.texture.MTextureManager with priority 1000 [PREINJECT Applicator Phase -> porting_lib.mixins.client.json:TextureManagerMixin from mod porting_lib -> Prepare Injections ->  -> handler$zcg000$porting_lib$port_lib$fixRelease(Lnet/minecraft/class_2960;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1060::port_lib$fixRelease with priority 1000 cannot inject into net/minecraft/class_1060::method_4615(Lnet/minecraft/class_2960;)V merged by net.vulkanmod.mixin.texture.MTextureManager with priority 1000 [PREINJECT Applicator Phase -> porting_lib.mixins.client.json:TextureManagerMixin from mod porting_lib -> Prepare Injections ->  -> handler$zcg000$porting_lib$port_lib$fixRelease(Lnet/minecraft/class_2960;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:306) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:241) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) [?:?]
	at net.minecraft.class_310.<init>(class_310.java:512) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:197) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.10.jar:?]
```

### Anything else?

fabric-api-0.77.0+1.18.2
TesseractAPI-fabric-0.2.2-1.18.2
AntimatterAPI-fabric-0.2-1.18.2
VulkanMod_1.18.2-0.2.5

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed Antimatter and Tesseract are up to date.

- [X] Yes

**Comment by Trinsdar** [comment]
Never looked at this till now, it's an conflict between porting lib and vulkan mod, not something I can fix
