### ISSUE TITLE
[Bug] common_setup event phase error

### ISSUE THREAD

**Issue by rchpweblo** [GregTech-Intergalactical/AntimatterAPI#233]
### What happened?

![image](https://github.com/GregTech-Intergalactical/AntimatterAPI/assets/23265365/e26c5d70-4d20-46fa-9f01-61904568dcc4)

Error encountered by doing the following:
Running 1.18.2 with the most recent version of 1.18.2 forge.
The only mods in the mod folder were a clean build of GTI and a clean build of Antimatter, made moments prior.
When running with GTI it throws this error, but when only running Antimatter API the game successfully starts.

### What mod loaders are you seeing the problem on?

Forge

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/21/24, 3:52 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.2.21-universal.jar%2361!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:170) ~[forge-1.18.2-40.2.21-universal.jar%2361!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:557) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:551) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.21.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	GT Core (gtcore), Version: 0.1.1-pre29
		Issue tracker URL: https://github.com/GregTech-Intergalactical/GT-Utility
		at TRANSFORMER/gtcore@0.1.1-pre29/io.github.gregtechintergalactical.gtcore.tree.block.BlockRubberStairs.<init>(BlockRubberStairs.java:15)
Stacktrace:
	at io.github.gregtechintergalactical.gtcore.tree.block.BlockRubberStairs.<init>(BlockRubberStairs.java:15) ~[gtcore-forge-0.1.1-pre29-1.18.2.jar%2381!/:unspecified] {re:classloading}
-- MOD antimatter --
Details:
	Mod File: /C:/Users/rchpw/Documents/My Games/Minecraft/Instances/GreggaFirmaCraft 1.18.2/mods/AntimatterAPI-forge-0.2.1-pre37-1.18.2.jar
	Failure message: AntimatterAPI (antimatter) encountered an error during the common_setup event phase
		java.lang.NoSuchMethodError: 'net.minecraft.world.level.block.state.BlockState muramasa.antimatter.block.BlockBasic.n()'
	Mod Version: 0.2.1-pre37
	Mod Issue URL: https://github.com/GregTech-Intergalactical/AntimatterAPI/issues
	Exception message: java.lang.NoSuchMethodError: 'net.minecraft.world.level.block.state.BlockState muramasa.antimatter.block.BlockBasic.n()'
Stacktrace:
	at io.github.gregtechintergalactical.gtcore.tree.block.BlockRubberStairs.<init>(BlockRubberStairs.java:15) ~[gtcore-forge-0.1.1-pre29-1.18.2.jar%2381!/:unspecified] {re:classloading}
	at io.github.gregtechintergalactical.gtcore.data.GTCoreBlocks.<clinit>(GTCoreBlocks.java:57) ~[gtcore-forge-0.1.1-pre29-1.18.2.jar%2381!/:unspecified] {re:classloading}
	at io.github.gregtechintergalactical.gtcore.GTCore.onRegistrationEvent(GTCore.java:97) ~[gtcore-forge-0.1.1-pre29-1.18.2.jar%2381!/:unspecified] {re:classloading}
	at muramasa.antimatter.AntimatterAPI.lambda$onRegistration$27(AntimatterAPI.java:415) ~[AntimatterAPI-forge-0.2.1-pre37-1.18.2.jar%2354!/:0.2.1-pre37-1.18.2] {re:mixin,re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at muramasa.antimatter.AntimatterAPI.onRegistration(AntimatterAPI.java:415) ~[AntimatterAPI-forge-0.2.1-pre37-1.18.2.jar%2354!/:0.2.1-pre37-1.18.2] {re:mixin,re:classloading}
	at muramasa.antimatter.registration.forge.AntimatterRegistration.onRegister(AntimatterRegistration.java:70) ~[AntimatterAPI-forge-0.2.1-pre37-1.18.2.jar%2354!/:0.2.1-pre37-1.18.2] {re:classloading}
	at muramasa.antimatter.registration.forge.AntimatterRegistration.onRegister(AntimatterRegistration.java:51) ~[AntimatterAPI-forge-0.2.1-pre37-1.18.2.jar%2354!/:0.2.1-pre37-1.18.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_32_AntimatterRegistration_onRegister_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.21.jar%2358!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:123) ~[fmlcore-1.18.2-40.2.21.jar%2357!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:42) ~[fmlcore-1.18.2-40.2.21.jar%2357!/:?] {}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:26) ~[fmlcore-1.18.2-40.2.21.jar%2357!/:?] {}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:202) ~[fmlcore-1.18.2-40.2.21.jar%2357!/:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.21.jar%2357!/:?] {re:mixin}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.21.jar%2357!/:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.21.jar%2357!/:?] {re:mixin}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.21.jar%2357!/:?] {re:mixin}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:92) ~[forge-1.18.2-40.2.21-universal.jar%2361!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.18.2-40.2.21-universal.jar%2361!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:92) ~[forge-1.18.2-40.2.21-universal.jar%2361!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:459) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.21.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3198476760 bytes (3050 MiB) / 5167382528 bytes (4928 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX TITAN X
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x17c2
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5152
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 1.33
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 1.33
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 50114.95
	Virtual memory used (MB): 27475.09
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 320.25
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		arrp-forge-0.6.7.jar                              |Runtime Resource Pack Forge   |arrp                          |0.6.7               |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.11.jar               |MixinExtras                   |mixinextras                   |0.2.0-beta.11       |COMMON_SET|Manifest: NOSIGNATURE
		TesseractAPI-forge-0.2.3-1.18.2.jar               |TesseractAPI                  |tesseractapi                  |0.2.3               |COMMON_SET|Manifest: NOSIGNATURE
		resourcefullib-forge-1.18.2-0.0.5.jar             |Resourceful Lib               |resourcefullib                |0.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		botarium-forge-1.18.2-2.0.5.jar                   |Botarium                      |botarium                      |2.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.2.21-universal.jar                |Forge                         |forge                         |40.2.21             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		terraform-utils-v1-3.1.5.jar                      |Terraform Utils               |terraform_utils               |3.1.5               |COMMON_SET|Manifest: NOSIGNATURE
		terraform-wood-api-v1-3.1.5.jar                   |Terraform Wood API (v1) Reforg|terraform_wood_api_v1         |3.1.5               |COMMON_SET|Manifest: NOSIGNATURE
		AntimatterAPI-forge-0.2.1-pre37-1.18.2.jar        |AntimatterAPI                 |antimatter                    |0.2.1-pre37         |ERROR     |Manifest: NOSIGNATURE
		gtcore-forge-0.1.1-pre29-1.18.2.jar               |GT Core                       |gtcore                        |0.1.1-pre29         |COMMON_SET|Manifest: NOSIGNATURE
		gti-forge-0.2.1-pre39-1.18.2.jar                  |GTI                           |gti                           |0.2.1-pre39         |COMMON_SET|Manifest: NOSIGNATURE
		structurelib-forge-2.0.0-pre10-1.18.2.jar         |Structure Lib                 |structurelib                  |2.0.0-pre10         |COMMON_SET|Manifest: NOSIGNATURE
		carbon-config-L3ipBBnb.jar                        |Carbon Config Library         |carbonconfig                  |1.18.2-1.1.4        |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: dec2d151-675b-4835-aeba-d76ae161bafd
	FML: 40.2
	Forge: net.minecraftforge:40.2.21
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed Antimatter and Tesseract are up to date.

- [x] Yes

**Comment by Trinsdar** [comment]
don't try compiling the mod and then running it, sometimes stuff breaks in the latest commits. also I'm already aware of this issue
